### ISSUE TITLE
Arduino implementation

### ISSUE THREAD

**Issue by msalero** [PaulStoffregen/AVR_DTMF#2]
Hi! Paul.
I find you code very detailed as for use in DTMF projects. I am woking in a DTMF implementation using Arduino and I think it would be of great help for me. Do you know if your code has been adapted for Arduino use? - Thanks in advance for your comments.

Regards,

MS

**Comment by PaulStoffregen** [comment]
Sorry, there's no support for this free software.

Maybe ask on the Arduino forum.  Github issues are not the place to ask for help.
